import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/core.css";
import "@/styles/demo.css";
import "@/styles/cards-statistics.css";
import "@/styles/node-waves.css";
import "@/styles/perfect-scrollbar.css";
import Script from "next/script";
import Sidebar from "@/components/admin/layout/sidebar";
import Footer from "@/components/admin/footer/Footer";
import Header from "@/components/admin/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* Left Fixed Sidebar */}
        <div className="w-64 h-screen fixed left-0 top-0 border-r bg-white">
          <Sidebar />
        </div>

        {/* Main Content (Footer + Pages) */}
        <div className="ml-64 min-h-screen flex flex-col">
            <Header />
          <main className="flex-1 p-4">{children}</main>
          <Footer />
        </div>

        <Script src="/vendor/js/helpers.js" strategy="beforeInteractive" />
        <Script src="/js/config.js" strategy="afterInteractive" />
        <Script
          src="/vendor/js/template-customizer.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
